<a href="https://colab.research.google.com/github/dobrevajovana/Makedonizer/blob/main/Sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers
!pip install torch

     |████████████████████████████████| 3.8 MB 5.2 MB/s 
     |████████████████████████████████| 596 kB 44.2 MB/s 
     |████████████████████████████████| 895 kB 38.5 MB/s 
     |████████████████████████████████| 6.5 MB 41.3 MB/s 
     |████████████████████████████████| 67 kB 4.5 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# import glob
# list_of_models = glob.glob("/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/*")

In [ ]:
list_of_models = ['/content/drive/MyDrive/macedonizer.finki/mk-roberta-common-crawl/checkpoint-3800000']

In [ ]:
import re

def atoi(text):
    return int(text) if text.isdigit() else text

def natural_keys(text):
    '''
    alist.sort(key=natural_keys) sorts in human order
    http://nedbatchelder.com/blog/200712/human_sorting.html
    (See Toothy's implementation in the comments)
    '''
    return [atoi(c) for c in re.split(r'(\d+)', text) ]

alist=list_of_models

alist.sort(key=natural_keys)
print(alist)

['/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-10000', '/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-20000', '/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-30000', '/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-40000', '/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-60000', '/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-80000', '/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-100000', '/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-120000', '/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-140000', '/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-160000', '/content/drive/MyDrive/MakedonizerSentimentAnalysis/RoBERTa-Models/checkpoint-180000', '/content/drive/MyDrive/MakedonizerSe

In [ ]:
alist = alist[82:]

In [ ]:
alist = list_of_models

In [ ]:
alist

['/content/drive/MyDrive/macedonizer.finki/mk-roberta-common-crawl/checkpoint-3800000']

In [ ]:
tokenizer_path = '/content/drive/MyDrive/macedonizer.finki/mk-roberta-tokenizer'

In [ ]:
import os
import random

import pandas as pd
import numpy as np


import torch
from torch.utils.data import RandomSampler, DataLoader, TensorDataset, SequentialSampler
from transformers import get_linear_schedule_with_warmup, AdamW
from transformers import RobertaForSequenceClassification

from torch import cuda
from tqdm import tqdm

import transformers
from transformers import RobertaModel, RobertaTokenizer

from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix, classification_report, matthews_corrcoef
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [ ]:
# df = pd.read_excel('/content/drive/MyDrive/MakedonizerSentimentAnalysis/Sentiment-Analysis-Dataset/time.mk ekonomija.xlsx')

In [ ]:
# print(df)
# is_NaN = df.isnull()
# row_has_NaN = is_NaN.any(axis=1)
# rows_with_NaN = df[row_has_NaN]
# print(rows_with_NaN)
# 11 redica vo samiot dataset ima NaN vrednost!

In [ ]:
# df.dropna(subset = ["label"], inplace=True)

In [ ]:
# df

In [ ]:
# df['label'] = df['label'].astype('|S')

In [ ]:
# from sklearn.preprocessing import LabelEncoder

# encoder = LabelEncoder()
# df['label'] = encoder.fit_transform(df['label'])

In [ ]:
# df['label'].unique()

In [ ]:
# new_df = df[['abstract', 'label']]

In [ ]:
# X_train, X_test, Y_train, Y_test = train_test_split(new_df.index.values, new_df.label.values, test_size = 0.15, random_state = 42, stratify=new_df.label.values)

In [ ]:
# new_df['data_type'] = ['not_set'] * new_df.shape[0]

In [ ]:
# new_df.loc[X_train, 'data_type'] = 'train'
# new_df.loc[X_test, 'data_type'] = 'val'

In [ ]:
# new_df.groupby(['label', 'data_type']).count()

In [ ]:
# new_df.to_csv('/content/drive/MyDrive/MakedonizerSentimentAnalysis/Sentiment-Analysis-Dataset/dataset.csv', index=False)

In [ ]:
new_df = pd.read_csv('/content/drive/MyDrive/macedonizer.finki/Evaluation Tasks/Sentiment Analysis/MakedonizerSentimentAnalysisRobertaBaseAll/Sentiment-Analysis-Dataset/dataset.csv')

In [ ]:
new_df

abstract  label data_type
0    Со инвестиција од 4,7 милиони евра швајцарски ...      1     train
1    Во септември годинава продолжи трендот на нама...      1     train
2    Продолжување на работното време, укинување на ...      0     train
3    Од 1 јануари годинава целосно е либерализиран ...      1     train
4    Во 2016 година „Аџибадем Систина“ беше првата ...      1       val
..                                                 ...    ...       ...
637  Германскиот производител на спортска облека „А...      0     train
638  Хотелот „Континентал“, земјиштето под него как...      0     train
639  Дел тутунари од Прилепско денеска еден час го ...      0     train
640  Секој петти работник во Македонија бил жртва н...      0     train
641  Бројот на работниците во индустријата во декем...      0       val

[642 rows x 3 columns]

In [ ]:
MAX_LEN = 256
TRAIN_BATCH_SIZE = 8
VALID_BATCH_SIZE = 4

tokenizer = RobertaTokenizer.from_pretrained(tokenizer_path, truncation=True)

In [ ]:
encoded_data_train = tokenizer.batch_encode_plus(
    new_df[new_df.data_type == 'train'].abstract.values,
    add_special_tokens=True,
    return_attention_mask=True,
    pad_to_max_length=True,
    max_length=256,
    return_tensors='pt'
)

encoded_data_val = tokenizer.batch_encode_plus(
    new_df[new_df.data_type == 'val'].abstract.values,
    add_special_tokens=True,
    return_attention_mask=True,
    pad_to_max_length=True,
    max_length=256,
    return_tensors='pt'
)

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2277: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


In [ ]:
input_ids_train = encoded_data_train['input_ids']
attention_mask_train = encoded_data_train['attention_mask']
labels_train = torch.tensor(new_df[new_df.data_type == 'train'].label.values)

In [ ]:
input_ids_val = encoded_data_val['input_ids']
attention_mask_val = encoded_data_val['attention_mask']
labels_val = torch.tensor(new_df[new_df.data_type == 'val'].label.values)

In [ ]:
dataset_train = TensorDataset(input_ids_train, attention_mask_train, labels_train)
dataset_val = TensorDataset(input_ids_val, attention_mask_val, labels_val)

In [ ]:
label_dict = {}
possible_labels = new_df.label.unique()

In [ ]:
for index, possible_label in enumerate(possible_labels):
  label_dict[possible_label] = index

In [ ]:
dataloader_train = DataLoader(
    dataset_train,
    sampler=RandomSampler(dataset_train),
    batch_size=TRAIN_BATCH_SIZE
)

dataloader_val = DataLoader(
    dataset_val,
    sampler=RandomSampler(dataset_val),
    batch_size=VALID_BATCH_SIZE
)

In [ ]:
def f1_score_func(preds, labels):
  preds_flat = np.argmax(preds, axis=1).flatten()
  labels_flat = labels.flatten()
  return f1_score(labels_flat, preds_flat, average='weighted')

In [ ]:
def accuracy_score_func(preds, labels):
  preds_flat = np.argmax(preds, axis=1).flatten()
  labels_flat = labels.flatten()
  return accuracy_score(labels_flat, preds_flat)

In [ ]:
def precision_score_func(preds, labels):
  preds_flat = np.argmax(preds, axis=1).flatten()
  labels_flat = labels.flatten()
  return precision_score(labels_flat, preds_flat)

In [ ]:
def recall_score_func(preds, labels):
  preds_flat = np.argmax(preds, axis=1).flatten()
  labels_flat = labels.flatten()
  return recall_score(labels_flat, preds_flat)

In [ ]:
def matthews_corrcoef_func(preds, labels):
  preds_flat = np.argmax(preds, axis=1).flatten()
  labels_flat = labels.flatten()
  return matthews_corrcoef(labels_flat, preds_flat)

In [ ]:
def single_model_performance(preds, labels):
  preds_flat = np.argmax(preds, axis=1).flatten()
  labels_flat = labels.flatten()
  print("Confusion Matrix:")
  print(confusion_matrix(y_true=labels_flat, y_pred=preds_flat))
  print(classification_report(y_true=labels_flat, y_pred=preds_flat))
  print(f'MCC score: {matthews_corrcoef(y_true=labels_flat, y_pred=preds_flat)}')

In [ ]:
def evaluate(dataloader_val):

    model.eval()

    loss_val_total = 0
    predictions, true_vals = [], []

    for batch in tqdm(dataloader_val):

        batch = tuple(b.to(device) for b in batch)

        inputs = {'input_ids':      batch[0],
                  'attention_mask': batch[1],
                  'labels':         batch[2],
                 }

        with torch.no_grad():
            outputs = model(**inputs)

        loss = outputs[0]
        logits = outputs[1]
        loss_val_total += loss.item()

        logits = logits.detach().cpu().numpy()
        label_ids = inputs['labels'].cpu().numpy()
        predictions.append(logits)
        true_vals.append(label_ids)

    loss_val_avg = loss_val_total/len(dataloader_val)

    predictions = np.concatenate(predictions, axis=0)
    true_vals = np.concatenate(true_vals, axis=0)

    return loss_val_avg, predictions, true_vals

In [ ]:
epochs = 10

In [ ]:
from tqdm.notebook import tqdm

for model_checkpoint in alist:

  model_path = model_checkpoint
  checkpoint = model_checkpoint.split("/")[-1]

  model = RobertaForSequenceClassification.from_pretrained(
    model_path,
    num_labels = len(label_dict)
    )

  LEARNING_RATE = 1e-05

  optimizer = AdamW(
      model.parameters(),
      lr=LEARNING_RATE,
      eps=1e-8
  )

  scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps = 0,
    num_training_steps = len(dataloader_train) * epochs
  )

  seed_val = 17
  random.seed(seed_val)
  np.random.seed(seed_val)
  torch.manual_seed(seed_val)
  torch.cuda.manual_seed_all(seed_val)

  device = 'cuda' if cuda.is_available() else 'cpu'

  model.to(device)
  print(f'Training: {checkpoint}')

  for epoch in tqdm(range(1, epochs + 1)):
    model.train()
    loss_train_total = 0

    progress_bar = tqdm(dataloader_train,
                        desc='Epoch {:1d}'.format(epoch),
                        leave=False,
                        disable=False)

    for batch in progress_bar:
      model.zero_grad()
      batch = tuple(b.to(device) for b in batch)
      inputs = {
          'input_ids': batch[0],
          'attention_mask': batch[1],
          'labels': batch[2]
      }

      outputs = model(**inputs)
      loss = outputs[0]
      loss_train_total += loss.item()
      loss.backward()

      torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

      optimizer.step()
      scheduler.step()

      progress_bar.set_postfix({'training_loss': '{:.3f}'.format(loss.item()/len(batch))})

    loss_train_avg = loss_train_total/len(dataloader_train)
    print(f'Epoch: {epoch}')
    tqdm.write(f'Training loss: {loss_train_avg}')

    val_loss, predictions, true_vals = evaluate(dataloader_val)
    val_f1 = f1_score_func(predictions, true_vals)
    print(f'Validation loss: {val_loss}')
    print(f'F1 Score (weighted): {val_f1}')
    single_model_performance(predictions, true_vals)
    print('')

    f1_s = f1_score_func(predictions, true_vals)
    acc_s = accuracy_score_func(predictions, true_vals)
    prec_s = precision_score_func(predictions, true_vals)
    rec_s = recall_score_func(predictions, true_vals)
    mcc_s = matthews_corrcoef_func(predictions, true_vals)

    dictionary = {
    'Model Checkpoint' : checkpoint,
    'Accuracy Score' : acc_s,
    'Precision Score' : prec_s,
    'Recall Score' : rec_s,
    'F1 Score' : f1_s,
    'MCC Score' : mcc_s
    }

  if not os.path.exists('/content/drive/MyDrive/Macedonizer-Evaluation/SentimentAnalysis/Results/results.csv'):
    df_results = pd.DataFrame(dictionary, index=[0])
    df_results.to_csv('/content/drive/MyDrive/Macedonizer-Evaluation/SentimentAnalysis/Results/results.csv')
    continue

  results = pd.read_csv('/content/drive/MyDrive/Macedonizer-Evaluation/SentimentAnalysis/Results/results.csv')
  results = results.append(dictionary, ignore_index=True)
  results.to_csv('/content/drive/MyDrive/Macedonizer-Evaluation/SentimentAnalysis/Results/results.csv', index=False)

Some weights of the model checkpoint at /content/drive/MyDrive/macedonizer.finki/mk-roberta-common-crawl/checkpoint-3800000 were not used when initializing RobertaForSequenceClassification: ['lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.bias', 'lm_head.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at /content/drive/MyDrive/macedonizer.finki/mk

Training: checkpoint-3800000


  0%|          | 0/10 [00:00<?, ?it/s]

Epoch 1:   0%|          | 0/69 [00:00<?, ?it/s]

Epoch: 1
Training loss: 0.6044682000858196


  0%|          | 0/25 [00:00<?, ?it/s]

Validation loss: 0.4383698880672455
F1 Score (weighted): 0.8002100991791714
Confusion Matrix:
[[29 14]
 [ 5 49]]
              precision    recall  f1-score   support

           0       0.85      0.67      0.75        43
           1       0.78      0.91      0.84        54

    accuracy                           0.80        97
   macro avg       0.82      0.79      0.80        97
weighted avg       0.81      0.80      0.80        97

MCC score: 0.6057794102477225



Epoch 2:   0%|          | 0/69 [00:00<?, ?it/s]

Epoch: 2
Training loss: 0.3889343080961186


  0%|          | 0/25 [00:00<?, ?it/s]

Validation loss: 0.29005041360855105
F1 Score (weighted): 0.8749050461204557
Confusion Matrix:
[[34  9]
 [ 3 51]]
              precision    recall  f1-score   support

           0       0.92      0.79      0.85        43
           1       0.85      0.94      0.89        54

    accuracy                           0.88        97
   macro avg       0.88      0.87      0.87        97
weighted avg       0.88      0.88      0.87        97

MCC score: 0.751840863007551



Epoch 3:   0%|          | 0/69 [00:00<?, ?it/s]

Epoch: 3
Training loss: 0.24419889536996683


  0%|          | 0/25 [00:00<?, ?it/s]

Validation loss: 0.3139808067120612
F1 Score (weighted): 0.885606769680607
Confusion Matrix:
[[35  8]
 [ 3 51]]
              precision    recall  f1-score   support

           0       0.92      0.81      0.86        43
           1       0.86      0.94      0.90        54

    accuracy                           0.89        97
   macro avg       0.89      0.88      0.88        97
weighted avg       0.89      0.89      0.89        97

MCC score: 0.7718100762465359



Epoch 4:   0%|          | 0/69 [00:00<?, ?it/s]

Epoch: 4
Training loss: 0.14601389671999798


  0%|          | 0/25 [00:00<?, ?it/s]

Validation loss: 0.33806049048900605
F1 Score (weighted): 0.9169869607385323
Confusion Matrix:
[[37  6]
 [ 2 52]]
              precision    recall  f1-score   support

           0       0.95      0.86      0.90        43
           1       0.90      0.96      0.93        54

    accuracy                           0.92        97
   macro avg       0.92      0.91      0.92        97
weighted avg       0.92      0.92      0.92        97

MCC score: 0.834277401804255



Epoch 5:   0%|          | 0/69 [00:00<?, ?it/s]

Epoch: 5
Training loss: 0.08801183010370511


  0%|          | 0/25 [00:00<?, ?it/s]

Validation loss: 0.44057004488538953
F1 Score (weighted): 0.8742103967841616
Confusion Matrix:
[[33 10]
 [ 2 52]]
              precision    recall  f1-score   support

           0       0.94      0.77      0.85        43
           1       0.84      0.96      0.90        54

    accuracy                           0.88        97
   macro avg       0.89      0.87      0.87        97
weighted avg       0.88      0.88      0.87        97

MCC score: 0.7555528938210088



Epoch 6:   0%|          | 0/69 [00:00<?, ?it/s]

Epoch: 6
Training loss: 0.05989167603083711


  0%|          | 0/25 [00:00<?, ?it/s]

Validation loss: 0.4272935368772596
F1 Score (weighted): 0.8742103967841616
Confusion Matrix:
[[33 10]
 [ 2 52]]
              precision    recall  f1-score   support

           0       0.94      0.77      0.85        43
           1       0.84      0.96      0.90        54

    accuracy                           0.88        97
   macro avg       0.89      0.87      0.87        97
weighted avg       0.88      0.88      0.87        97

MCC score: 0.7555528938210088



Epoch 7:   0%|          | 0/69 [00:00<?, ?it/s]

Epoch: 7
Training loss: 0.05134572258279861


  0%|          | 0/25 [00:00<?, ?it/s]

Validation loss: 0.4438881186512299
F1 Score (weighted): 0.8742103967841616
Confusion Matrix:
[[33 10]
 [ 2 52]]
              precision    recall  f1-score   support

           0       0.94      0.77      0.85        43
           1       0.84      0.96      0.90        54

    accuracy                           0.88        97
   macro avg       0.89      0.87      0.87        97
weighted avg       0.88      0.88      0.87        97

MCC score: 0.7555528938210088



Epoch 8:   0%|          | 0/69 [00:00<?, ?it/s]

Epoch: 8
Training loss: 0.049535956424391035


  0%|          | 0/25 [00:00<?, ?it/s]

Validation loss: 0.4592770836642012
F1 Score (weighted): 0.8742103967841616
Confusion Matrix:
[[33 10]
 [ 2 52]]
              precision    recall  f1-score   support

           0       0.94      0.77      0.85        43
           1       0.84      0.96      0.90        54

    accuracy                           0.88        97
   macro avg       0.89      0.87      0.87        97
weighted avg       0.88      0.88      0.87        97

MCC score: 0.7555528938210088



Epoch 9:   0%|          | 0/69 [00:00<?, ?it/s]

Epoch: 9
Training loss: 0.044465790052250355


  0%|          | 0/25 [00:00<?, ?it/s]

Validation loss: 0.4866292954678647
F1 Score (weighted): 0.884332162682678
Confusion Matrix:
[[33 10]
 [ 1 53]]
              precision    recall  f1-score   support

           0       0.97      0.77      0.86        43
           1       0.84      0.98      0.91        54

    accuracy                           0.89        97
   macro avg       0.91      0.87      0.88        97
weighted avg       0.90      0.89      0.88        97

MCC score: 0.7797560284387783



Epoch 10:   0%|          | 0/69 [00:00<?, ?it/s]

Epoch: 10
Training loss: 0.038861257855888405


  0%|          | 0/25 [00:00<?, ?it/s]

Validation loss: 0.7208513778285124
F1 Score (weighted): 0.884332162682678
Confusion Matrix:
[[33 10]
 [ 1 53]]
              precision    recall  f1-score   support

           0       0.97      0.77      0.86        43
           1       0.84      0.98      0.91        54

    accuracy                           0.89        97
   macro avg       0.91      0.87      0.88        97
weighted avg       0.90      0.89      0.88        97

MCC score: 0.7797560284387783

